### ISSUE TITLE
Remove time.sleep from _call method

### ISSUE THREAD

**Issue by ipetukhov** [AnthonyBloomer/zoopla#3]
Hi,

It's really not the best way of error processing. Could you return exception in case when rate limit reached?

**Comment by AnthonyBloomer** [comment]
By default, the program throws an exception if the rate limit has reached. If you pass wait_on_rate_limit = True in the constructor then the program will sleep until it can request data again. 

wait_on_rate_limit is an optional argument in the constructor so you can just leave it out. For example:

```python
zoopla = Zoopla(api_key='your_api_key', debug=True)
```
