### ISSUE TITLE
Prices not visible 

### ISSUE THREAD

**Issue by ibegleris** [AnthonyBloomer/zoopla#5]
Hello, 
It seems that the example in the readme does not give price in the output dictionary. 

`from zoopla import Zoopla`

`zoopla = `Zoopla(api_key='***************')`

`search = zoopla.property_listings({`
   ` 'maximum_beds': 2,`
   ` 'page_size': 100,`
   ` 'listing_status': 'sale',`
   ` 'area': 'Blackley, Greater Manchester'`
`})`

`'price' in result`
`False`

**Comment by AnthonyBloomer** [comment]
Hi @ibegleris,

The price was missing from the PropertyListingSchema. I've pushed a fix there.

**Comment by ibegleris** [comment]
I can confirm! Thanks.
