### ISSUE TITLE
Simple query raises zoopla.exceptions.ResponseFormatException

### ISSUE THREAD

**Issue by thomasleese** [AnthonyBloomer/zoopla#6]
This looks like a really great library, thanks for making it!

I'm just struggling to get it working correctly, I've got the following code which is raising an exception for me.

```python
from zoopla import Zoopla

zoopla = Zoopla(api_key='...')

search = zoopla.property_listings({
    'area': "London",
    'listing_status': "rent",
    'page_size': 100,
})
```

I'm getting a `zoopla.exceptions.ResponseFormatException` exception on some fields being null.

**Comment by AnthonyBloomer** [comment]
Hi @thomasleese,

Glad you like the lib.

I was able to replicate your issue and have pushed a fix.

I will publish to PyPi now!

**Comment by thomasleese** [comment]
Thank you very much!
